### ISSUE TITLE
It crashes on my machine

### ISSUE THREAD

**Issue by ngryman** [muan/dashboard#10]
Hey @muan, it seems that it crashes on my machine:
![image](https://user-images.githubusercontent.com/892048/34652423-dda718d4-f3dd-11e7-9d90-b2613688c204.png)

It seems related to the fact that the `.news .alert` selector does not work anymore, probably the markup has changed?
![image](https://user-images.githubusercontent.com/892048/34652486-1d911ca0-f3df-11e7-85bd-b5a6cfe4447d.png)

**Comment by muan** [comment]
Oh that's very possible. I'm not using this extension anymore personally, but I can take a look some time.
