### ISSUE TITLE
Filtering commits and repo pushes

### ISSUE THREAD

**Issue by SamTebbs33** [muan/dashboard#5]
Would you add a new filter option that filters out commits and pushes to the repo?

**Comment by muan** [comment]
Not sure I know what you mean, you can perhaps submit a PR?

**Comment by SamTebbs33** [comment]
Well, I mean an option in the dashboard to filter out commits to repos that you are watching, as there's currently no option for that.

**Comment by muan** [comment]
This extension is using the class names in the markup to create filter and would have no way of knowing if the user is watching a specific repository, such function would be out of the scope of this extension.
