### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by cbetta** [muan/dashboard#8]
I've been missing the icons for a while. Is this just me?

![screen shot 2016-06-06 at 14 24 21](https://cloud.githubusercontent.com/assets/7718/15823396/6232092a-2bf2-11e6-9296-a8142a2a92aa.png)

**Comment by muan** [comment]
Not just you! we got rid of octicon the font and are now using SVGs. Instead of adding the new icons I thought we can do without the check. Will make a release :soon:.

**Comment by cbetta** [comment]
Got the new version! Thanks!
